# Generated by Django 2.2.2 on 2019-10-27 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_male', models.BinaryField(blank=True, null=True)),
                ('audio_female', models.BinaryField(blank=True, null=True)),
                ('native_text', models.TextField()),
                ('ipa', models.TextField()),
                ('romanization', models.TextField(blank=True, null=True)),
                ('roman_alt', models.TextField(blank=True, null=True)),
                ('pinyin', models.TextField(blank=True, null=True)),
                ('pinyin_alt', models.TextField(blank=True, null=True)),
                ('zhuyin', models.TextField(blank=True, null=True)),
                ('chinese_alt', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='decks.Language')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='decks.Sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='decks.Sentence')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClozeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splice_start', models.SmallIntegerField()),
                ('splice_end', models.SmallIntegerField()),
                ('mult_choice0', models.TextField()),
                ('mult_choice1', models.TextField()),
                ('mult_choice2', models.TextField()),
                ('mult_choice3', models.TextField()),
                ('answer', models.SmallIntegerField()),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='decks.Translation')),
            ],
        ),
    ]
